### ISSUE TITLE
thread 'main' panicked at 'byte index 10 is not a char boundary; it is inside '❌' (bytes 9..12) of `n    <td>❌</td>`', src/libcore/str/mod.rs:2034:5

### ISSUE THREAD

**Issue by bbigras** [xd009642/tarpaulin#236]
I have this error when I use `❌` in an askama template.

rustc 1.36.0-nightly (7c71bc320 2019-04-30)
cargo-tarpaulin version: 0.8.3

I seem able to reproduce with:

```rust
fn main() {
    println!("<td>❌</td>");
}
```

```
thread 'main' panicked at 'byte index 5 is not a char boundary; it is inside '❌' (bytes 4..7) of `<td>❌</td>`', src/libcore/str/mod.rs:2034:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
   9: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}
  10: <cargo_tarpaulin::report::safe_json::SafeFormatter as serde_json::ser::Formatter>::write_string_fragment
  11: serde_json::ser::format_escaped_str
  12: cargo_tarpaulin::report::html::_IMPL_SERIALIZE_FOR_SourceFile::<impl serde::ser::Serialize for cargo_tarpaulin::report::html::SourceFile>::serialize
  13: serde::ser::Serializer::collect_seq
  14: cargo_tarpaulin::report::html::_IMPL_SERIALIZE_FOR_CoverageReport::<impl serde::ser::Serialize for cargo_tarpaulin::report::html::CoverageReport>::serialize
  15: cargo_tarpaulin::report::safe_json::to_string_safe
  16: cargo_tarpaulin::report::html::export
  17: cargo_tarpaulin::report_coverage
  18: cargo_tarpaulin::run
  19: cargo_tarpaulin::main
  20: std::rt::lang_start::{{closure}}
  21: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  23: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  24: main
  25: __libc_start_main
  26: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by xd009642** [comment]
Sorry for the delay but I've fixed this and pushed it to the develop branch. I'll just do a release now for 0.8.4 as well :+1:
