### ISSUE TITLE
Panic with SSH Github dependencies in manifest

### ISSUE THREAD

**Issue by jmagnuson** [xd009642/tarpaulin#319]
This issue emerged in `tarpaulin` 0.10.0 and is specifically related to https://github.com/servo/rust-url/issues/577, but `cargo` has recently worked around in https://github.com/rust-lang/cargo/pull/7787. The next `cargo` release (>0.41.0) should contain this fix, but as https://github.com/xd009642/tarpaulin/pull/307 suggests, it will be a manual process to upgrade.

<details><summary>RUST_BACKTRACE=full cargo tarpaulin</summary>
<p>

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55d16df61d94 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55d16df61d94 - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55d16df61d94 - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x55d16df61d94 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55d16df8bf9c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x55d16df5c7b7 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x55d16df6574e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55d16df6574e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55d16df6574e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x55d16df65441 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x55d16df65e4b - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x55d16df659ee - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x55d16df658d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:302
  13:     0x55d16df8870e - core::panicking::panic_fmt::hdeb7979ab6591473
                               at src/libcore/panicking.rs:139
  14:     0x55d16df88807 - core::result::unwrap_failed::h054dd680e6fcd38b
                               at src/libcore/result.rs:1165
  15:     0x55d16d50f6f2 - core::result::Result<T,E>::unwrap::h839095a8f510cacd
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933
  16:     0x55d16d3be37f - cargo::util::canonical_url::CanonicalUrl::new::h7e27b17bee6f9489
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/canonical_url.rs:42
  17:     0x55d16ce62527 - cargo::core::source::source_id::SourceId::new::h96e31d07553f70e7
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/core/source/source_id.rs:82
  18:     0x55d16ce64bf9 - cargo::core::source::source_id::SourceId::for_git::h0d40b23eab0a432a
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/core/source/source_id.rs:168
  19:     0x55d16d12b3c7 - cargo::util::toml::DetailedTomlDependency::to_dependency::h2d6d0cedf8860d81
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:1433
  20:     0x55d16d1287cf - cargo::util::toml::TomlDependency::to_dependency::h720f55c0dfb26809
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:1330
  21:     0x55d16d124133 - cargo::util::toml::TomlManifest::to_real_manifest::process_dependencies::h0139e54c77f59e87
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:936
  22:     0x55d16d11e89f - cargo::util::toml::TomlManifest::to_real_manifest::h97e305e48ca81223
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:944
  23:     0x55d16d117e6b - cargo::util::toml::do_read_manifest::h52a4797f15c7ea4a
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:79
  24:     0x55d16d1173b8 - cargo::util::toml::read_manifest::h42a61dbfea9b1687
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/util/toml/mod.rs:41
  25:     0x55d16d2b75e3 - cargo::core::workspace::Packages::load::hfd5cfd6271cdd97c
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/core/workspace.rs:839
  26:     0x55d16d2acea4 - cargo::core::workspace::Workspace::find_root::h212aeeaf71f73818
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/core/workspace.rs:378
  27:     0x55d16d2ab645 - cargo::core::workspace::Workspace::new::h53df395e008dae3d
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.40.0/src/cargo/core/workspace.rs:143
  28:     0x55d16c663b83 - cargo_tarpaulin::launch_tarpaulin::hb52218098a73d265
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.10.0/src/lib.rs:79
  29:     0x55d16c6630bf - cargo_tarpaulin::run::h41401f2c881718d9
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.10.0/src/lib.rs:39
  30:     0x55d16c5034bc - cargo_tarpaulin::main::hf06db68806d3a56a
                               at /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.10.0/src/main.rs:113
  31:     0x55d16c5068c5 - std::rt::lang_start::{{closure}}::h3279c050fdcec6e8
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  32:     0x55d16df65873 - std::rt::lang_start_internal::{{closure}}::h6ea535ec5c50fc3e
                               at src/libstd/rt.rs:48
  33:     0x55d16df65873 - std::panicking::try::do_call::h631c6408dfccc6f5
                               at src/libstd/panicking.rs:287
  34:     0x55d16df6fd4a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  35:     0x55d16df663ed - std::panicking::try::hab539b2d1255d635
                               at src/libstd/panicking.rs:265
  36:     0x55d16df663ed - std::panic::catch_unwind::hd5e0a26424bd7f34
                               at src/libstd/panic.rs:396
  37:     0x55d16df663ed - std::rt::lang_start_internal::h3bdc4c7d98181bf9
                               at src/libstd/rt.rs:47
  38:     0x55d16c506899 - std::rt::lang_start::he59d5586b5b173b7
                               at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  39:     0x55d16c50371a - main
  40:     0x7efcbb629b97 - __libc_start_main
  41:     0x55d16c5026ea - _start
  42:                0x0 - <unknown>
```

</p>
</detail>

**Comment by xd009642** [comment]
I've just updated cargo to 0.41.0 and it can be found in the develop branch. I plan on cutting a new release tomorrow or Thursday so the fix will be in master when that happens and I'll close the issue then

**Comment by holmesmr** [comment]
This apparently didn't make it into `cargo` 0.42.0, so this is still broken in 0.11.0.

**Comment by xd009642** [comment]
That's a shame, but at least with depend bot I'll get a PR updating it opened as soon as it's released and then I'll cut a new release 👍
