### ISSUE TITLE
Regression with latest version v0.12.0

### ISSUE THREAD

**Issue by bburnichon** [xd009642/tarpaulin#391]
I am currently running coverages with tarpaulin.

It seems binaries are not ignored anymore when testing.

* Linux 5.3.0-45-generic #37-Ubuntu SMP Thu Mar 26 20:41:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* rustc 1.42.0 (b8cedc004 2020-03-09)

```
Replaced package `cargo-tarpaulin v0.10.2` with `cargo-tarpaulin v0.11.1` (executable `cargo-tarpaulin`)
$ cargo tarpaulin -v
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
    Finished dev [unoptimized + debuginfo] target(s) in 0.65s
[DEBUG tarpaulin] Processing Target(bin: binary1)
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/bburnichon/prog/target/debug/deps/binary1-0d4918b82dbf666b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
80.52% coverage, 1583/1966 lines covered
```
```
$ cargo install cargo-tarpaulin
    Updating crates.io index
  Installing cargo-tarpaulin v0.12.0
   Replacing /home/bburnichon/.cargo/bin/cargo-tarpaulin
    Replaced package `cargo-tarpaulin v0.11.1` with `cargo-tarpaulin v0.12.0` (executable `cargo-tarpaulin`)
```
```
$ cargo tarpaulin -v
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
    Finished test [unoptimized + debuginfo] target(s) in 0.19s
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/bburnichon/prog/target/debug/mylib-c0314bbf21a60e8d
[DEBUG tarpaulin] Instrumentation address clash, ignoring 0x54fa10
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/bburnichon/prog/target/debug/binary1
Error: Os { code: 98, kind: AddrInUse, message: "Address already in use" }
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/bburnichon/prog/target/debug/binary2
thread 'main' panicked at 'Could not find runtime API env var: environment variable not found', <::std::macros::panic macros>:5:6
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: lambda_runtime_core::runtime::start_with_config
             at ./<::std::macros::panic macros>:5
  14: lambda_runtime::start
             at /home/bburnichon/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_runtime-0.2.1/src/lib.rs:109
  15: lambda_http::start
             at /home/bburnichon/.cargo/registry/src/github.com-1ecc6299db9ec823/lambda_http-0.1.1/src/lib.rs:106
  16: mslambda::main
             at src/mslambda.rs:138
  17: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: "Test failed during run"
```

**Comment by xd009642** [comment]
Do you have an public project for me to try this on? Just to understand which binaries are being ran which shouldn't be

**Comment by bburnichon** [comment]
Sadly, this project is not public. But binaries ran that shouldn't be are the binaries declared in Cargo.toml. The main functions also have the `#cfg_attr(tarpaulin, skip)` above.

```bash
$ cargo new test-tarpaulin
     Created binary (application) `test-tarpaulin` package
$ cat <<EOF > src/main.rs 
> #[cfg_attr(tarpaulin, skip)]
> fn main() {
>     println!("Hello, world!");
>     panic!("Should not be called");
> }
> 
> EOF
$ cargo tarpaulin
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/bburnichon/test-tarpaulin/target/debug/test_tarpaulin-1955d1b57e1741e6

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Error: "Failed to report coverage! Error: No coverage results collected."
```
Here is a minimal program to reproduce

**Comment by Licenser** [comment]
I got the same issue had to fall back to 0.11 failing build is here if it helps: https://github.com/simd-lite/simd-json/pull/120/checks?check_run_id=571688648 it seems to be related to features on my end

**Comment by xd009642** [comment]
Cool, I noticed some stuff in cargo metadata that should fix the issue. I'll use simd-json to test any fixes and hopefully have something by the end of Friday :+1:

**Comment by Licenser** [comment]
btw I know I only write tickets when something doesn't work so I'll add it here, tarpaulin is awesome!

**Comment by tonyfinn** [comment]
I think it might be related, but it also seems to be running main() when you have a project with integration tests, reproducible example here: https://github.com/tonyfinn/tarpaulin-repro

**Comment by xd009642** [comment]
I've now got a fix for the example in that example, if the CI passes I'll push out a qucik release and that should be most of the 0.12.x regressions hopefully tackled :crossed_fingers:

**Comment by xd009642** [comment]
0.12.2 was released this should hopefully fix these regressions so if people could check and report back that would be appreciated :+1:

**Comment by bburnichon** [comment]
I've just tested new release. It does not fail anymore. Thank you for prompt support and your amazing work!

**Comment by tonyfinn** [comment]
Can also confirmed this fixed the problem on my project also
