### ISSUE TITLE
Invalid unicode character (d805) when processing `librustc_expand`

### ISSUE THREAD

**Issue by 0x7CFE** [xd009642/tarpaulin#409]
cargo-tarpaulin version: 0.12.3
rustc repo revision https://github.com/rust-lang/rust/commit/5a59527516a917738c2e5f5d9f5e9a3533a6a5bc
Linux epsilon 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
rustc 1.44.0-nightly (b2e36e6c2 2020-04-22)

I tried running tarpaulin on a `librustc_expand` which is a part of `rustc`. Unfortunately it crashed with the following backtrace:

```
korvin@epsilon:~/work/research/rust/rust/src/librustc_expand$ RUST_BACKTRACE=1 cargo tarpaulin -v --run-types Tests --out Stdout
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
    Finished test [unoptimized] target(s) in 0.14s
thread 'main' panicked at 'character code d805 is not a valid unicode character', /home/korvin/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.18/src/lit.rs:1261:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:515
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: syn::lit::value::backslash_u
  14: syn::lit::value::parse_lit_str
  15: syn::lit::value::<impl syn::lit::Lit>::new
  16: syn::parse::ParseBuffer::step
  17: <syn::lit::Lit as syn::token::Token>::peek::peek
  18: <syn::lit::Lit as syn::token::Token>::peek
  19: syn::expr::parsing::atom_expr
  20: syn::expr::parsing::trailer_expr
  21: syn::expr::parsing::unary_expr
  22: syn::expr::parsing::ambiguous_expr
  23: syn::stmt::parsing::parse_stmt
  24: syn::stmt::parsing::<impl syn::stmt::Block>::parse_within
  25: syn::item::parsing::<impl syn::parse::Parse for syn::item::ItemFn>::parse
  26: syn::item::parsing::<impl syn::parse::Parse for syn::item::Item>::parse
  27: syn::file::parsing::<impl syn::parse::Parse for syn::file::File>::parse
  28: syn::parse::Parser::parse_str
  29: syn::parse_file
  30: cargo_tarpaulin::source_analysis::get_line_analysis
  31: cargo_tarpaulin::launch_tarpaulin
  32: cargo_tarpaulin::trace
  33: cargo_tarpaulin::run
  34: cargo_tarpaulin::main
  35: std::rt::lang_start::{{closure}}
  36: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  37: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  38: std::panicking::try
             at src/libstd/panicking.rs:274
  39: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  40: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  41: main
  42: __libc_start_main
  43: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by xd009642** [comment]
So I've tracked it down to `rust/src/test/ui/parser/new-unicode-escapes-2.rs` when I try to run source analysis on this it fails, because it's not valid unicode. I'll raise an issue in syn and see if they're willing to tackle it. Otherwise I guess using exclude-files to exclude to the tests/ui package should work

**Comment by 0x7CFE** [comment]
Awesome, thanks for the feedback!

**Comment by 0x7CFE** [comment]
> So I've tracked it down to `rust/src/test/ui/parser/new-unicode-escapes-2.rs` when I try to run source analysis on this it fails, because it's not valid unicode. I'll raise an issue in syn and see if they're willing to tackle it. Otherwise I guess using exclude-files to exclude to the tests/ui package should work

Hm. Actually I was running tarpaulin whilst inside `librustc_expand` directory, whereas `new-unicode-escapes-2.rs` is outside. How could it affect the local test build?

P.S.: I've commented out that test and it still crashes. So maybe there's something else.

**Comment by xd009642** [comment]
But it's part of a workspace so can refer to other packages in the workspace as they could be included in the results

**Comment by xd009642** [comment]
Didn't mean to close this I just have fat fingers :grimacing:. I was trying to do this again but failed to figure out how to run the tests on the version of rustc_expand I have checked out
