### ISSUE TITLE
Tarpaulin 0.18.0-alpha1 fails after a `cargo build`

### ISSUE THREAD

**Issue by winksaville** [xd009642/tarpaulin#736]
**Describe the bug**
When using Tarpaulin 0.18.0-alpha1 installed from a clone of this project:
```
wink@3900x:~/prgs/rust/clone/tarpaulin (develop)
$ git log -1 --pretty=oneline
2eb72209c908b5fe3be55cfeb2da4d723f103d2f (HEAD -> develop, origin/develop, origin/HEAD) Bump syn from 1.0.68 to 1.0.69 (#735)

wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo tarpaulin --version
cargo-tarpaulin version: 0.18.0-alpha1
```
I get the following error when I compile [winksaville/binance-auto-sell](https://github.com/winksaville/rust-binance-auto-sell/tree/tarpaulin-requires-cargo-clean):
```
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'already borrowed: BorrowMutError', src/tools/cargo/src/cargo/util/config/mod.rs:307:20
```

If instead I use the release version, 0.16.0:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo tarpaulin --version
cargo-tarpaulin version: 0.16.0
```
It completes successfully:
```
Apr 14 12:02:48.687  INFO cargo_tarpaulin: Launching test
Apr 14 12:02:48.687  INFO cargo_tarpaulin: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/binance_auto_sell-8b2f8d3614c3ece0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Apr 14 12:02:49.267  INFO cargo_tarpaulin: Launching test
Apr 14 12:02:49.267  INFO cargo_tarpaulin: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/cli-595a799ae4fee77f

running 4 tests
test test_req_params_as_env_vars ... ok
test test_req_params ... ok
test test_no_params ... ok
test test_help ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

Apr 14 12:02:50.331  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| src/main.rs: 16-17, 20-22, 24
|| Tested/Total Lines:
|| src/main.rs: 0/6
|| 
0.00% coverage, 0/6 lines covered
```
> But note: the **0.00% coverage**! Hence the reason to use 0.18.0 as it supports `--follow-exec`

**To Reproduce**

Here is the command line and full output. Notice that this happens after a `cargo build`:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo clean && cargo build && RUST_BACKTRACE=1 cargo tarpaulin --verbose
   Compiling proc-macro2 v1.0.26
   Compiling version_check v0.9.3
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling autocfg v1.0.1
   Compiling libc v0.2.93
   Compiling unicode-segmentation v1.7.1
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling hashbrown v0.9.1
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling os_str_bytes v2.4.0
   Compiling lazy_static v1.4.0
   Compiling vec_map v0.8.2
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished dev [unoptimized + debuginfo] target(s) in 7.49s
Apr 14 11:56:52.713 DEBUG cargo_tarpaulin: set up logging
Apr 14 11:56:52.733  INFO cargo_tarpaulin: Running Tarpaulin
Apr 14 11:56:52.733  INFO cargo_tarpaulin: Building project
   Compiling autocfg v1.0.1
   Compiling version_check v0.9.3
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling memchr v2.3.4
   Compiling libc v0.2.93
   Compiling syn v1.0.69
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling unicode-segmentation v1.7.1
   Compiling doc-comment v0.3.3
   Compiling predicates-core v1.0.2
   Compiling hashbrown v0.9.1
   Compiling regex-syntax v0.6.23
   Compiling unicode-width v0.1.8
   Compiling byteorder v1.4.3
   Compiling vec_map v0.8.2
   Compiling normalize-line-endings v0.3.0
   Compiling treeline v0.1.0
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling os_str_bytes v2.4.0
   Compiling difference v2.0.0
   Compiling textwrap v0.12.1
   Compiling predicates-tree v1.0.2
   Compiling regex-automata v0.1.9
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.14
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling aho-corasick v0.7.15
   Compiling bstr v0.2.15
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling wait-timeout v0.2.0
   Compiling float-cmp v0.8.0
   Compiling regex v1.4.5
   Compiling predicates v1.0.7
   Compiling assert_cmd v1.0.3
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
error: could not compile `binance-auto-sell`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'already borrowed: BorrowMutError', src/tools/cargo/src/cargo/util/config/mod.rs:307:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: cargo::core::compiler::job_queue::DrainState::drain_the_queue
   4: std::panic::catch_unwind
   5: crossbeam_utils::thread::scope
   6: cargo::core::compiler::job_queue::JobQueue::execute
   7: cargo::core::compiler::context::Context::compile
   8: cargo::ops::cargo_compile::compile_ws
   9: cargo::ops::cargo_compile::compile
  10: cargo::ops::cargo_test::run_tests
  11: cargo::commands::test::exec
  12: cargo::cli::main
  13: cargo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Apr 14 11:57:01.006 ERROR cargo_tarpaulin: Failed to compile tests! Error: binance-auto-sell: linking with `cc` failed: exit code: 1
Error: "Failed to compile tests! Error: binance-auto-sell: linking with `cc` failed: exit code: 1"
```

**Work-around**
If I do a `cargo clean` before the `cargo tarpaulin` it works:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo clean && cargo build && cargo clean && RUST_BACKTRACE=1 cargo tarpaulin --verbose
   Compiling proc-macro2 v1.0.26
   Compiling version_check v0.9.3
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling libc v0.2.93
   Compiling autocfg v1.0.1
   Compiling unicode-segmentation v1.7.1
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling hashbrown v0.9.1
   Compiling termcolor v1.1.2
   Compiling vec_map v0.8.2
   Compiling strsim v0.10.0
   Compiling os_str_bytes v2.4.0
   Compiling lazy_static v1.4.0
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished dev [unoptimized + debuginfo] target(s) in 7.41s
Apr 14 12:19:25.789 DEBUG cargo_tarpaulin: set up logging
Apr 14 12:19:26.003  INFO cargo_tarpaulin: Running Tarpaulin
Apr 14 12:19:26.003  INFO cargo_tarpaulin: Building project
   Compiling autocfg v1.0.1
   Compiling version_check v0.9.3
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling memchr v2.3.4
   Compiling libc v0.2.93
   Compiling syn v1.0.69
   Compiling unicode-segmentation v1.7.1
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling doc-comment v0.3.3
   Compiling predicates-core v1.0.2
   Compiling byteorder v1.4.3
   Compiling hashbrown v0.9.1
   Compiling unicode-width v0.1.8
   Compiling regex-syntax v0.6.23
   Compiling treeline v0.1.0
   Compiling normalize-line-endings v0.3.0
   Compiling os_str_bytes v2.4.0
   Compiling difference v2.0.0
   Compiling vec_map v0.8.2
   Compiling termcolor v1.1.2
   Compiling strsim v0.10.0
   Compiling textwrap v0.12.1
   Compiling predicates-tree v1.0.2
   Compiling regex-automata v0.1.9
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling num-traits v0.2.14
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling aho-corasick v0.7.15
   Compiling bstr v0.2.15
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling wait-timeout v0.2.0
   Compiling float-cmp v0.8.0
   Compiling regex v1.4.5
   Compiling predicates v1.0.7
   Compiling assert_cmd v1.0.3
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished test [unoptimized + debuginfo] target(s) in 8.20s
Apr 14 12:19:34.457  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 14 12:19:34.457  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/binance_auto_sell-8b2f8d3614c3ece0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Apr 14 12:19:35.040  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 14 12:19:35.040  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/cli-595a799ae4fee77f

running 4 tests
test test_req_params_as_env_vars ... ok
test test_req_params ... ok
test test_no_params ... ok
test test_help ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.07s

Apr 14 12:19:36.115  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| src/main.rs: 16-17, 20-22, 24
|| Tested/Total Lines:
|| src/main.rs: 0/6
|| 
0.00% coverage, 0/6 lines covered
```
And if I add the `--follow-exec` parameter I see the expected **100.00% coverage**:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo tarpaulin --verbose --follow-exec
Apr 14 12:20:39.852 DEBUG cargo_tarpaulin: set up logging
Apr 14 12:20:39.871  INFO cargo_tarpaulin: Running Tarpaulin
Apr 14 12:20:39.871  INFO cargo_tarpaulin: Building project
    Finished test [unoptimized + debuginfo] target(s) in 0.01s
Apr 14 12:20:39.930  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 14 12:20:39.930  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/cli-595a799ae4fee77f

running 4 tests
test test_no_params ... ok
test test_help ... ok
test test_req_params_as_env_vars ... ok
test test_req_params ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.28s

Apr 14 12:20:43.230  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 14 12:20:43.230  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/binance_auto_sell-8b2f8d3614c3ece0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Apr 14 12:20:43.793  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| Tested/Total Lines:
|| src/main.rs: 6/6 +100%
|| 
100.00% coverage, 6/6 lines covered, +100% change in coverage
```
**Expected behavior**
The version 0.18.0-alpha1 should behave the same as 0.16.0.

**System information**
Arch Linux:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ uname -a
Linux 3900x 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux
```
output of `rustup show`:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/wink/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-2021-03-25-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu

installed targets for active toolchain
--------------------------------------

thumbv7em-none-eabihf
thumbv7m-none-eabi
x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (overridden by '/home/wink/prgs/rust/projects/binance-auto-sell/rust-toolchain')
rustc 1.51.0 (2fd73fabe 2021-03-23)
```
My rust-toolchain file:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cat rust-toolchain 
[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev" ]
profile = "minimal"
```

**Comment by xd009642** [comment]
So there was a cargo PR about this that was meant to fix it. I tried to use the latest nightly for your project with the latest nightly compiler just to make sure I was using a version of cargo with the fix in and instead I encountered ICE https://github.com/rust-lang/rust/issues/84225 . 

Tomorrow is the start of my weekend so I'll set aside some time to more thoroughly diff 0.16.0 and 0.18.0-alpha1 to try and see what changed and also try it out on some other projects to get to the bottom of it.

**Comment by winksaville** [comment]
@xd009642, txs for looking into this.

This evening, I'll try to simplify the code.

**Comment by winksaville** [comment]
I've simplified the code its on my [tarpaulin-requires-cargo-clean](https://github.com/winksaville/rust-binance-auto-sell/tree/tarpaulin-requires-cargo-clean) branch.

main.rs is as simple as I could get:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cat src/main.rs
use clap::Clap;

#[derive(Clap)]
struct Cli {}

fn main() {
    Cli::parse(); // Fails
    //Cli {}; // Works
}
```
tests/cli.rs is empty
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ ls -al tests
total 8
drwxr-xr-x 2 wink users 4096 Apr 15 21:54 .
drwxr-xr-x 6 wink users 4096 Apr 15 22:11 ..
-rw-r--r-- 1 wink users    0 Apr 15 21:48 cli.rs
```
In Cargo.toml I've removed the `[dev-dependencies]`
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cat Cargo.toml 
[package]
name = "binance-auto-sell"
version = "0.1.0"
authors = ["Wink Saville <wink@saville.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
```
rust-toolchain is still stable
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cat rust-toolchain 
[toolchain]
channel = "stable"
components = [ "rustfmt", "rustc-dev" ]
profile = "minimal"
```
And tarpaulin is still 0.18.0-alpha1
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo tarpaulin --version
cargo-tarpaulin version: 0.18.0-alpha1
```
And running `cargo clean ; cargo build ; cargo tarpaulin` still fails:
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo clean ; cargo build ; cargo tarpaulin
   Compiling proc-macro2 v1.0.26
   Compiling version_check v0.9.3
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling libc v0.2.93
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling unicode-segmentation v1.7.1
   Compiling unicode-width v0.1.8
   Compiling hashbrown v0.9.1
   Compiling vec_map v0.8.2
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling lazy_static v1.4.0
   Compiling os_str_bytes v2.4.0
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished dev [unoptimized + debuginfo] target(s) in 7.38s
Apr 15 22:18:10.142  INFO cargo_tarpaulin: Running Tarpaulin
Apr 15 22:18:10.142  INFO cargo_tarpaulin: Building project
   Compiling proc-macro2 v1.0.26
   Compiling version_check v0.9.3
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling libc v0.2.93
   Compiling autocfg v1.0.1
   Compiling unicode-segmentation v1.7.1
   Compiling bitflags v1.2.1
   Compiling unicode-width v0.1.8
   Compiling hashbrown v0.9.1
   Compiling termcolor v1.1.2
   Compiling strsim v0.10.0
   Compiling os_str_bytes v2.4.0
   Compiling lazy_static v1.4.0
   Compiling vec_map v0.8.2
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
error: could not compile `binance-auto-sell`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'already borrowed: BorrowMutError', src/tools/cargo/src/cargo/util/config/mod.rs:307:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 15 22:18:17.719 ERROR cargo_tarpaulin: Failed to compile tests! Error: binance-auto-sell: linking with `cc` failed: exit code: 1
Error: "Failed to compile tests! Error: binance-auto-sell: linking with `cc` failed: exit code: 1"
```
But if I comment out `Cli::parse();` and uncomment `Cli::{};`
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cat src/main.rs 
use clap::Clap;

#[derive(Clap)]
struct Cli {}

fn main() {
    //Cli::parse(); // Fails
    Cli {}; // Works
}
```
It "works":
```
wink@3900x:~/prgs/rust/projects/binance-auto-sell (tarpaulin-requires-cargo-clean)
$ cargo clean ; cargo build ; cargo tarpaulin
   Compiling version_check v0.9.3
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling libc v0.2.93
   Compiling autocfg v1.0.1
   Compiling bitflags v1.2.1
   Compiling unicode-segmentation v1.7.1
   Compiling unicode-width v0.1.8
   Compiling hashbrown v0.9.1
   Compiling os_str_bytes v2.4.0
   Compiling strsim v0.10.0
   Compiling lazy_static v1.4.0
   Compiling termcolor v1.1.2
   Compiling vec_map v0.8.2
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished dev [unoptimized + debuginfo] target(s) in 7.19s
Apr 15 22:20:52.004  INFO cargo_tarpaulin: Running Tarpaulin
Apr 15 22:20:52.004  INFO cargo_tarpaulin: Building project
   Compiling proc-macro2 v1.0.26
   Compiling version_check v0.9.3
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling autocfg v1.0.1
   Compiling libc v0.2.93
   Compiling bitflags v1.2.1
   Compiling unicode-segmentation v1.7.1
   Compiling hashbrown v0.9.1
   Compiling unicode-width v0.1.8
   Compiling os_str_bytes v2.4.0
   Compiling vec_map v0.8.2
   Compiling lazy_static v1.4.0
   Compiling strsim v0.10.0
   Compiling termcolor v1.1.2
   Compiling textwrap v0.12.1
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.6.2
   Compiling heck v0.3.2
   Compiling quote v1.0.9
   Compiling atty v0.2.14
   Compiling clap_derive v3.0.0-beta.2
   Compiling clap v3.0.0-beta.2
   Compiling binance-auto-sell v0.1.0 (/home/wink/prgs/rust/projects/binance-auto-sell)
    Finished test [unoptimized + debuginfo] target(s) in 7.33s
Apr 15 22:20:59.385  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 15 22:20:59.385  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/cli-780735ec9073a7ff

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Apr 15 22:20:59.458  INFO cargo_tarpaulin::process_handling::linux: Launching test
Apr 15 22:20:59.458  INFO cargo_tarpaulin::process_handling: running /home/wink/prgs/rust/projects/binance-auto-sell/target/debug/deps/binance_auto_sell-cc700bcd52a31b50

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

Apr 15 22:21:00.030  INFO cargo_tarpaulin::report: Coverage Results:
|| Tested/Total Lines:
|| src/main.rs: 0/1
|| 
0.00% coverage, 0/1 lines covered
```
I hope this makes identifing the problem easier. Let me know if there is anything you'd like me to do!

**Comment by xd009642** [comment]
So it looks like this may have been indirectly caused by https://github.com/rust-lang/rust/pull/84226 . I'll change tarpaulin to clean by default to solve it and then remove that option once this makes it into stable

**Comment by xd009642** [comment]
So 0.18.0-alpha2 is now released that fixes the issue until that rust PR makes it into the 1.53.0 stable, checked it and it works as expected :+1:

**Comment by winksaville** [comment]
Txs for adding --skip-clean!
